version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - stocktonkincade
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.13
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.1
    - 2.38.4
    - 2.38.5
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.42.0
    - 2.42.3
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.7
    - 3.13.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.21.0
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
